# -*- coding: utf-8 -*-
"""Project Part 2 Aya & Ana.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kA2y-1DUimw1UC1eRlzUc9XlRf5r5yzw
"""

import sqlite3
from sqlite3.dbapi2 import DatabaseError

import pandas as pd
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

#df_participants=pd.read_excel('/content/drive/MyDrive/participants.xlsx')
#df_countries=pd.read_excel('/content/drive/MyDrive/countries.xlsx')
#df_projects=pd.read_excel('/content/drive/MyDrive/projects.xlsx')

con= sqlite3.connect('exel_database.db')
df_projects.to_sql('projects',con, if_exists='replace', index= False)
df_countries.to_sql('countries',con, if_exists='replace', index= False)
df_participants.to_sql('participants',con, if_exists='replace', index= False)

con.close()
df_projects.head()

database = exel_database.db
selects= {
'country':
'''SELECT Acronym FROM countries WHERE Country = "{}" ''',

'grants':
'''SELECT SUM (O.ecContribution) AS grants
  FROM organizations o JOIN projects p ON o.projectID==p.projectID
  WHERE o.country = '{}'
  GROUP BY p.year''',

'participants':
'''SELECT shortName, o.name, p.acronym, p.keywords
  FROM organizations
  WHERE country = '{}'
  GROUP BY name ORDER BY SUM(ecContribution) DESC''',

'coordinators':
'''SELECT o.shortName